import CheckoutPageUI from '@/components/CheckoutPageUI/CheckoutPageUI'
import { BRAND_NAME } from '@/constants'
import Head from 'next/head'

const Checkout = () => {
  return (
    <>
      <Head>
        <title>{BRAND_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={'page_wrapper'}>
        <CheckoutPageUI />
      </div>
    </>
  )
}
export default Checkout
