import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import { ACCESS_TYPES, BRAND_NAME } from '@/constants'
import { useDispatch, useSelector } from 'react-redux'
import {
  CategorySectionSlider,
  HeroSection,
  CategorySelectionSection,
} from '@/components'
import dataHandler from '@/services/data-handler'
import { useEffect } from 'react'
import {
  getCountriesRequest,
  userLoginRequest,
  userLogOutRequest,
} from '@/store/slicers/user'
import { getBannerRequest } from '@/store/slicers/general'
import { store } from '@/store/store'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const state = useSelector((state) => state)
  const dispatch = useDispatch()
  // console.log({ state }, dataHandler.store.getState().user.user.jwt)

  useEffect(() => {
    // dispatch(
    //   getCountriesRequest({
    //     payload: null,
    //     responseCallback: (status, resp) => {
    //       console.log({ resp })
    //     },
    //   })
    // )
    // dataHandler.getStore().dispatch(userLoginRequest())
  }, [])
  return (
    <>
      <Head>
        <title>{BRAND_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page_wrapper}>
        <HeroSection />
        <CategorySectionSlider />
        <CategorySelectionSection />
      </div>
    </>
  )
}

export async function getServerSideProps() {
  // const dispatch = use Dispatch()
  // dataHandler.getStore().dispatch(getBannerRequest())
  const data = await getBannerRequest()
  // Pass data to the page via props
  return {
    props: {
      accessType: ACCESS_TYPES.PUBLIC,
    },
  }
}
