import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useDispatch, useSelector } from 'react-redux'
import styles from '@/styles/Login.module.scss'

import { useEffect } from 'react'
import { userLogOutRequest } from '@/store/slicers/user'

export default function Login() {
  const state = useSelector((state) => state)
  const dispatch = useDispatch()

  console.log({ state })

  useEffect(() => {
    dispatch(userLogOutRequest())
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.loginWrapper}>
        <h2>login</h2>
      </div>
    </>
  )
}
