import Head from 'next/head'
import styles from '@/styles/Login.module.scss'

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.loginWrapper}>
        <h2>login</h2>
      </div>
    </>
  )
}
