import Head from 'next/head'
import { BRAND_NAME } from '@/constants'
import SignUpPageUI from '@/components/SignUpPage/SignUpPageUI'

export default function SignUp() {
  return (
    <>
      <Head>
        <title>{BRAND_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page_wrapper_withoutmargin">
        <SignUpPageUI />
      </div>
    </>
  )
}
